### ISSUE TITLE
Memory leak in Loop

### ISSUE THREAD

**Issue by karl-malakoff** [icicleio/icicle#14]
I've found a memory leak inside the icicle loop when yielding from a co routine. 

This can be replicated with the below code:

``` php
<?php

require_once("./vendor/autoload.php");

use Icicle\Loop;
use Icicle\Coroutine\Coroutine;

function gen()
{
    while(true){
        yield array_fill(0, 10000, 4);
        print memory_get_usage(false).PHP_EOL;
    }
}

Loop\immediate(
    function() {
        new Coroutine(gen());
    }
);

Loop\Run();
```

This is possibly related to https://bugs.php.net/bug.php?id=69887 and https://bugs.php.net/bug.php?id=62210 which is reported to be fixed in php7.1.

**Comment by trowski** [comment]
This occurs due to an optimization made to the method used to executed queued callbacks in the loop. The coroutine engine uses queued callbacks to asynchronously continue coroutine execution and avoid blowing up the call stack. The values used in these callbacks is not removed until all callbacks in the current loop iteration are executed. Callbacks added during the same loop iteration will be run during the same iteration. This means each time the coroutine yielded an array, a reference would be kept until the next loop iteration. Since so much data was being produced, memory would run out before another loop iteration could occur and the arrays garbage collected.

See https://github.com/icicleio/icicle/blob/master/src/Loop/Structures/CallableQueue.php#L96-L115
`array_slice()` is not executed until all callbacks are executed, causing the arguments (in this case, the array generated by `array_fill()`) to build up in the queue.

I'll have to take a different approach to avoid hanging onto references longer than needed.
