### ISSUE TITLE
What is the best web framework for icicle to integrate in?

### ISSUE THREAD

**Issue by rylanathk** [icicleio/icicle#15]
I am going to make a whatsapp-like app and I wonder which framework is most suitable for icicle?

**Comment by mtymek** [comment]
I tried using one framework with Icicle - here's an example of how it can be integrated with Zend Expressive: https://github.com/mtymek/icicle-expressive/blob/master/bin/server.php.

**Comment by rylanathk** [comment]
@mtymek Thanks for reply! I will look into zend.

**Comment by trowski** [comment]
I plan on releasing a new version of the [HTTP package](https://github.com/icicleio/http) shortly that will have some considerable changes. Before you write too much code, let me tag that release since the way `Server` is used in that package changed significantly. See the example server in [`examples/server.php`](https://github.com/icicleio/http/blob/v0.3.x/examples/server.php).

You can integrate Icicle with several controller and router based frameworks. @assertchris might be able to provide some input on this, as I know he's experimented with a few.

**Comment by rylanathk** [comment]
@trowski  very looking forward to it :)
