### ISSUE TITLE
Fail to run the example code

### ISSUE THREAD

**Issue by rylanathk** [icicleio/icicle#16]
I cd to the directory where test.php locate and run `composer require icicle` and then copy the example code. But all of the examples in readme are failed. Here is a piece of the example code:

```
<?php

require 'vendor/autoload.php';
use Icicle\Coroutine\Coroutine;
use Icicle\Dns\Executor\Executor;
use Icicle\Dns\Resolver\Resolver;
use Icicle\Loop;
use Icicle\Socket\Client\Connector;

$generator = function () {
    try {
        $resolver = new Resolver(new Executor('8.8.8.8'));

        // This coroutine pauses until yielded coroutine is fulfilled or rejected.
        $ips = (yield $resolver->resolve('example.com'));

        $connector = new Connector();

        // This coroutine pauses again until yielded coroutine is fulfilled or rejected.
        $client = (yield $connector->connect($ips[0], 80));

        echo "Asynchronously connected to example.com:80\n";
    } catch (Exception $exception) {
        echo "Asynchronous task failed: {$exception->getMessage()}\n";
    }
};

$coroutine = new Coroutine($generator());

Loop\run();
?>
```

And I got a `Fetal error`: `Fatal error: Class 'Icicle\Dns\Resolver\Resolver' not found`

**Comment by trowski** [comment]
I've fallen behind on updating the readme on this repo since I'm preparing some formal docs that will be posted at [icicle.io/docs](https://icicle.io/docs). That example is out of date (plus you need to require the [DNS package](https://github.com/icicleio/dns) as well). Try requiring `icicleio/dns` and run the examples found in that package.

**Comment by rylanathk** [comment]
I have tried http://icicleio.github.io/docs/getting-started/ this example but still got the error `Class 'Icicle\Http\Server\Server' not found`

**Comment by trowski** [comment]
That example requires the `icicleio/http` package and is also out of date. Look at the examples found in that package. I'll try updating all the examples today or tomorrow. Clearly there needs to be some more basic examples on the getting started page that only rely on the base package.

**Comment by nexor** [comment]
Hello! I found strange bug in DNS package. The following code hangs up into endless loop and consumes 100% CPU:

``` php
#!/usr/bin/php
<?php

use Icicle\Coroutine;
use Icicle\Loop;
use Icicle\Http\Client\Client;

require __DIR__.'/vendor/autoload.php';

$generator = function() {
    echo "Connecting to server\n";
    $httpClient = new Client();

    $socket = yield from \Icicle\Dns\connect('www.google.com', 80);
    //$socket = yield from \Icicle\Dns\connect('77.37.250.212', 80);

    echo "Socket OK\n";
    echo $socket ? get_class($socket) : "NULL";
    echo "\n";
};

$coroutine = Coroutine\create($generator);

echo "RUN LOOP\n";
Loop\run();
```

composer.json:

``` json
{
    "minimum-stability": "dev",
    "require": {
        "icicleio/icicle": "~2.0",
        "icicleio/http": "*",
        "icicleio/dns": "*"
    }
}
```

console output:

``` bash
$ ./run.php 
Connecting to server
RUN LOOP

```

But if I use commented line `$socket = yield from \Icicle\Dns\connect('77.37.250.212', 80);` - all is OK:

``` bash
$ ./run.php 
Connecting to server
RUN LOOP
Socket OK
Icicle\Socket\NetworkSocket
```

Some additional info:

``` bash
$ php -v
PHP 7.0.2-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans
```

``` bash
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

Is it known problem?

**Comment by trowski** [comment]
@nexor This behavior was due to #17 that affects PHP 7.0.2. Your example code would hang in an infinite loop because the DNS lookup uses some code from the [stream package](https://github.com/icicleio/stream) that was affected by the bug. Using the IP address bypassed the affected code used by the DNS lookup. I've updated the stream package to avoid the bug, so run `composer update` and try again, it should work as expected now.

@yobichi The documentation at [icicle.io/docs](https://icicle.io/docs) has been updated with more examples to come. Please look there for examples and documentation. If you find any mistakes, please file an issue or PR on the repo at https://github.com/icicleio/docs.

**Comment by nexor** [comment]
Thanks! Now all works fine :+1:
